name: Enviro+ Python Library Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools tox pytest pytest-cov

      - name: Run Tests
        working-directory: library
        run: |
          tox -e py

      - name: Send Coveralls Report
        uses: coverallsapp/github-action@v2.2.0
        with:
          # Coveralls uses GITHUB_TOKEN to verify the posted coverage data.
          # It is builtin to GitHub Actions, so no need to set it up.
            github-token: ${{ secrets.GITHUB_TOKEN }}
